spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_dev
    username: sfg_dev_user
    password: guru
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    show-sql: true
    # properties:
    #   javax:
    #     persistence:
    #       schema-generation:
    #         scripts:
    #           action: create
    # create-target: guru_database_create.sql
