version: "3"
services:
  sfg_db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /Users/douuud/dev/learning/udemy/springframework-guru/spring5-recipe-app/scripts/mysql:/docker-entrypoint-initdb.d
      - sfg_db:/var/lib/mysql
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  sfg_db:
